P.register("cvfVersion",function(){return{version:"0.1.0.0-2024-02-27"}});"use strict";
P.when("A","cvfFormDataGenerator","cvf-client-side-counters-util","ready").register("cvf-account-switcher",function(a,l,b){function m(b,d){b.preventDefault();var c=l.retrieveFormData(b.target),h=c.inputData.serializeArray();h.push(e(b.target));a.ajax(window.location.protocol+"//"+window.location.host+c.requestPath,{method:"POST",params:h,success:d,error:f})}function e(a){a=h(a);var b=a.attr("name");b||(b=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var d=a.attr("value");d||
(d=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));return{name:b,value:d}}function f(b,d,c){a.trigger(r.error,c)}function c(a){var b=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);if(null!==b){a=b[1];a=h.trim(a);var d=a.length;if(1!==d){for(var c=a.charAt(0),e=0;e<d-2;e++)c+="*";a=c+=a.charAt(d-1)}a+="@";c=b[2];c=h.trim(c);d=c.length;c=c.charAt(0);for(e=0;e<d-1;e++)c+="*";return a+c+b[3]}b=h.trim(a);a=b.length;if(!(4>=a)){d="";for(c=0;c<a-4;c++)d+="*";b=d+b.substr(a-
4,a-1)}return b}function d(){0===h(".cvf-account-switcher-check-mark:visible").length&&(h(".cvf-account-switcher-check-mark-area").remove(),h(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}function g(d){var c=new URLSearchParams(window.location.search);c.delete("switch_to_cid");c.has("errorCodes")||c.append("errorCodes","ACCOUNT_SWITCH_FAILED");b.addMetricCount(d);a.trigger(r.error,"automaticAccountSwitchFailure");
window.location.search=c}function p(){if(0!==h(".cvf-switch-to-cid").length)try{b.startMetricTimer(n.latency);var c=h(".cvf-switch-to-cid")[0].getAttribute("value");h(".cvf-automatic-switch-"+c)[0].click();setTimeout(function(){g(n.failureTimeout)},7E3);a.trigger(r.success,"automaticAccountSwitchSuccess");return!0}catch(t){g(n.failureClicking)}finally{b.endMetricTimer(n.latency)}return!1}var h=a.$,r={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"},n={latency:"AutomaticAccountSwitch_Latency",
failureClicking:"AutomaticAccountSwitch_FailureClicking",failureTimeout:"AutomaticAccountSwitch_FailureTimeout"};(function(){var a=h("#ap-account-switcher-container")[0],b=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==b){var c=new b(function(a){for(var b=0;b<a.length;b++)if(null!==a[b].addedNodes){p()||d();c.disconnect();break}});c.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){h(".cvf-account-switcher-sign-out-link").live("click",
function(b){m(b,function(e){if(e.redirectUrl)window.location=e.redirectUrl,a.trigger("cvf:account_switcher","redirectOnSignOut");else if(e.succeeded){var f="."+h(b.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];h(f+"-hide").hide();h(f+"-name").text(h("#cvf-account-switcher-sign-out-replace-text").text());h(f+"-claim").text(c(h(f+"-claim").text()));h(f+"-image").replaceWith(h("\x3cdiv /\x3e").append(h("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());
h(f+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");e=e.switchedAccountId;void 0!==e&&h(".cvf-account-switcher-account-group-"+e+"-check-mark").show();d();window.location.reload()}else a.trigger(r.error,e)})})})();return{automaticAccountSwitch:p}});"use strict";
P.when("A","cvfInputValidatorConfig","ready").register("cvfInputValidator",function(a,l){return{getValidationResult:function(b){var m=!0,e=[],f=[];l.forEach(function(c){var d=a.$(c.invalidFieldAlertSelector),g=a.$(c.emptyFieldAlertSelector);c=b.find(c.inputSelector);c[0].required&&!c.val().trim()?(m=!1,0<g.length?(e.push(g),0<d.length&&f.push(d)):0<d.length&&e.push(d)):(0<g.length&&f.push(g),g=c[0].checkValidity&&!c[0].checkValidity(),m=m&&!g,d.length&&(g?e.push(d):f.push(d)))});return{isValid:m,
activeAlerts:e,inactiveAlerts:f}}}});"use strict";P.when("A","ready").register("cvfInputValidatorConfig",function(a){return[{inputSelector:".cvf-widget-input-code",invalidFieldAlertSelector:".cvf-widget-invalid-code-alert",emptyFieldAlertSelector:".cvf-widget-empty-field-alert"}]});P.register("a-sheet-wrapper",function(){return null});"use strict";
P.when("A","cvfFormDataGenerator","ready").register("cvfCaptcha",function(a,l){a=a.$;0===a(".cvf-widget-input-captcha").children("input").length?(a(".cvf-widget-input-captcha").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").attr("autocorrect","off")):(a(".cvf-widget-input-captcha").children("input").attr("autocapitalize","off"),a(".cvf-widget-input-captcha").children("input").attr("autocorrect","off"))});"use strict";
P.when("A").register("cvf-client-side-counters-util",function(a){function l(a,m){var b=window.ue;b&&"function"===typeof b.count&&(m||(m=(b.count(a)||0)+1),b.count(a,m))}return{incrementCounter:function(a){l(a)},insertCounter:l,addMetricCount:function(a){window.ue&&"function"===typeof window.ue.count&&window.ue.count(a,1)},startMetricTimer:function(a){window.uet&&"function"===typeof window.uet&&window.uet("bb",a,{wb:1})},endMetricTimer:function(a){window.uex&&"function"===typeof window.uex&&window.uex("ld",
a,{wb:1})}}});
P.when("A","3p-promise","a-alert","codeResendTimer","cvf-client-side-counters-util","sms-retriever-handler","ready").execute("client-sms-request-controller",function(a,l,b,m,e,f){function c(){a.show("#cvf-otp-autoread-progress");e.incrementCounter(u.SHOW_AUTOREAD_WIDGET);var b=d();x.delegate("#cvf-input-code","input",function(){clearTimeout(b);a.hide("#cvf-otp-autoread-progress");var c=n("#cvf-auto-read-status");c.val()!==t.AUTOREAD_TIMEOUT&&c.val()!==t.AUTOREAD_SUCCESS&&(e.incrementCounter(u.CANCEL_AUTOREAD_WIDGET),c.val(t.AUTOREAD_CANCELLED))})}
function d(){return setTimeout(function(){var c=n("#cvf-auto-read-status");a.hide("#cvf-otp-autoread-progress");e.incrementCounter(u.AUTOREAD_WIDGET_TIMEOUT);c.val(t.AUTOREAD_TIMEOUT);b("#cvf-otp-autoread-timeout").show()},3E4)}function g(b){y=b;b=n("#cvf-auto-read-status");k&&b.val()!==t.AUTOREAD_TIMEOUT&&b.val()!==t.AUTOREAD_CANCELLED&&(b=y,n("#cvf-auto-read-status").val(t.AUTOREAD_SUCCESS),n("#cvf-input-code").val(b).trigger("input"),a.show("#cvf-otp-autoread-success"),x.submit())}function p(a){m.createTimer(Number(a.timeRemaining),
n("#resend-timer-message-id").val(),n("#resend-timer-complete-id").val().replace(/"/g,""),"timer","timer",!1);a=n("#wait-resend-auto-read");a.submit(function(a){a.preventDefault()});n(".wait-one-minute-continue").click(function(){z.location.reload()});a.removeClass("aok-hidden");x.addClass("aok-hidden")}function h(){b("#otp-request-failed-alert").show();n("#cvf-input-code").attr("disabled","disabled").addClass("a-form-disabled");n("#cvf-submit-otp-button").addClass("a-button-disabled");n("#cvf-resend-link").unbind().click(function(){z.location.reload()})}
function r(b){a.get(b,{success:function(a){a.wait?(e.incrementCounter(u.WAIT_RESEND),p(a)):a.redirect?(e.incrementCounter(u.REDIRECT),z.location.replace(a.redirect)):(a=a.smsFormat)?(e.incrementCounter(u.RECEIVED_FORMAT+":"+a),"androidAutoReadSmsWithAppHash"===a&&(k=!0,c(),y&&g(y))):(e.incrementCounter(u.FORMAT_NOT_RECEIVED),console.error("Failed to receive sms format"))},error:function(a,b,c){e.incrementCounter(u.AJAX_SMS_REQUEST_FAILED+":"+c);h();console.error("Ajax request failed",c)}})}var n=
a.$,z=this;f=[f];var t=Object.freeze({AUTOREAD_SUCCESS:"autoreadWidgetSuccess",AUTOREAD_CANCELLED:"autoreadWidgetCancelled",AUTOREAD_TIMEOUT:"autoreadWidgetTimeout"}),u=Object.freeze({SHOW_AUTOREAD_WIDGET:"OTPAutoReadShowWidget",CANCEL_AUTOREAD_WIDGET:"OTPAutoReadCanceWidgetForManualInput",AUTOREAD_WIDGET_TIMEOUT:"OTPAutoReadWidgetTimeout",RECEIVED_FORMAT:"OTPAutoReadReceivedFormat",FORMAT_NOT_RECEIVED:"OTPAutoReadFormatNotReceived",REDIRECT:"OTPAutoReadClientRedirect",AJAX_SMS_REQUEST_FAILED:"OTPAutoReadAjaxSmsRequestFailed",
WAIT_RESEND:"OTPAutoReadWaitResend"}),w=a.state("autoReadAttrs");if(w&&w.isClientDrivenOtpSendingEnabled){var A=w.arbParam;if(A){var x=n("#verification-code-form");if(0!==x.length){var y=null,k=!1;a.capabilities.android?(f=f.map(function(a){return a.isEnabled().then(function(b){return b?a.registerListener(g).then(function(a){return a}):{}})}),l.all(f).then(function(a){var b=[],c={};a.forEach(function(a){a.handlerCapability&&b.push(a.handlerCapability);a.handlerQueryParams&&n.extend(c,a.handlerQueryParams)});
a={arb:A,mode:"page_ajax",sendClientDrivenOtp:!0,capabilities:b.join()};n.extend(a,c);a=z.location.origin+"/ap/cvf/request?"+n.param(a);r(a)})):(l=z.location.origin+"/ap/cvf/request?"+n.param({arb:A,mode:"page_ajax",sendClientDrivenOtp:!0}),r(l))}}}});"use strict";
P.when("A","ready").register("codeResendTimer",function(a){function l(m,e,f,c,d,g){var l=(new Date).getTime();g&&(clearInterval(b),window.localStorage.removeItem("icaCVFTimeId"));b=setInterval(function(){var h=(new Date).getTime()-l,r=m-h;g&&window.localStorage.setItem("icaCVFTimeId",r);0>=r?(clearInterval(b),g&&window.localStorage.removeItem("icaCVFTimeId"),g?(a.$("#"+c).hide(),a.$("#"+d).show()):a.$("#"+d).html(f)):(h=e.split(" +timeleft+ "),g?(r=(new Date(r)).toISOString().slice(14,19),h=h[0].split('"').join("")+
r+h[1].split('"').join("")):h=h[0].split('"').join("")+Math.floor(r/1E3)+h[1].split('"').join(""),a.$("#"+c).html(h))},100)}var b;return{createTimer:function(a,b,f,c,d,g){return new l(a,b,f,c,d,g)},showTimer:function(){a.$("#cvf-resend-link").hide();a.$("#cvf-resend-text").removeClass("cvf-hidden")}}});"use strict";
P.when("A","cvfFormDataGenerator","ready").execute(function(a,l){var b=a.$;b(".cvf-widget-btn-val").click(function(a){var e=b(a.target).closest(".cvf-widget-form");a=l.getNameValue(b(a.target));e.append('\x3cinput type\x3d"hidden" name\x3d"'+a.name+'" value\x3d"'+a.value+'"\x3e').submit()})});"use strict";
P.when("A","cvfVersion","cvfFormDataGenerator","cvfInputValidator","ready").register("cvf",function(a,l,b,m){function e(e){function h(b){"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",k.options.widgetMetricsScope,{wb:1});k.options.spinnerTarget&&k.options.spinnerTarget.hide();if(b.hasOwnProperty("error"))a.trigger(v.error,b.error);else if(b.redirectUrl)window.location=b.redirectUrl;else if(b.redirect){a.trigger(v.success,b.token,b.status,b.redirect);
if(k.options.showICALoadingAnimationOnSuccess){var d=c("#in-context-auth-loading-animation").prop("outerHTML");q.html(d)}k.options.autoDestroy?k.destroy():(c(".cvf-widget-alert").hide(),b.status?c(".cvf-widget-status-success").show():c(".cvf-widget-status-error").show(),y());a.trigger("cvf:verification:complete",b.status);q.find(".cvf-widget-btn").unbind("click",f);q.find(".cvf-widget-btn-val").unbind("click",f);a.off(v.success);a.off(v.error);a.off(v.content)}else q.html(b.replace(/<form/g,"\x3cdiv").replace(/<\/form/g,
"\x3c/div")),d=c(".cvf-widget-form-keep").clone().empty(),b=c(".cvf-widget-form-keep").children().clone(!0,!0),d=(new String(d.prop("outerHTML"))).replace(/<div/g,"\x3cform").replace(/<\/div/g,"\x3c/form"),c(".cvf-widget-form-keep").replaceWith(d),c(".cvf-widget-form-keep").html(b),w(),a.trigger(v.content)}function f(d,f,e){d.preventDefault();c(".cvf-widget-alert").hide();k.options.spinnerTarget&&k.options.spinnerTarget.show();var g=b.retrieveFormData(d.target,e);if(p()){if(k.options.showICAClaimUIOnClickChangeLink){k.options.showICAClaimUIOnClickChangeLink=
!1;k.options.spinnerTarget&&k.options.spinnerTarget.hide();d=c("#change-signin-claim-link-id").val();a.ajax(d,{method:"GET",dataType:"html",success:function(b){a.trigger("in-context-auth-content-update-event",b)},error:function(){c("#cvf-change-contact-link").hide();console.error("AJAX request to /ax/claim/ica failed.",this.error)}});return}if(e)q.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else if(e=m.getValidationResult(g.form),e.inactiveAlerts.forEach(function(a){a.hide()}),
e.activeAlerts.forEach(function(a){a.show()}),e.isValid)q.find(".cvf-widget-input").removeClass("cvf-widget-input-error");else{k.options.spinnerTarget&&k.options.spinnerTarget.hide();q.find(".cvf-widget-input").addClass("cvf-widget-input-error");t();u();return}}e=g.inputData.serializeArray();f&&e.push(b.getNameValue(d.target));a.ajax(B+g.requestPath,{method:"POST",params:e,success:h,error:x})}function n(a){13===a.keyCode&&f(a)}function p(){return 0<q.find('input[name\x3d"is_in_context_auth"]').length}
function t(){q.find('input[name\x3d"code"]').focus()}function u(){q.find('input[name\x3d"code"]').keypress(n)}function w(){q.find(".cvf-widget-btn").click(function(a){f(a,!1)});q.find(".cvf-widget-btn-val").click(function(a){f(a,!0)});p()||t();u();q.find(".cvf-widget-v2-link-resend").click(function(a){f(a,!1,!0)});q.find("#cvf-signin-with-password").click(function(a){a.preventDefault();q.find("#cvf-signin-with-password-instead-form").submit()});q.find(".cvf-widget-v2-change-contact-link").click(function(a){k.options.showICAClaimUIOnClickChangeLink=
!0;f(a,!1)})}function A(b){return function(c,d,e){"timeout"!==d||3<=C?a.trigger(v.error,e):a.delay(b,10*C++)}}function x(b,c,d){k.options.spinnerTarget&&k.options.spinnerTarget.hide();a.trigger(v.error,d)}function y(){c.each(q.find("input"),function(a,b){a=c(b);a.attr("disabled","disabled");a.hasClass("a-input-text")?a.addClass("a-form-disabled"):a.hasClass("a-button-input")?a.closest(".a-button").addClass("a-button-disabled"):a.closest(".a-input-text-wrapper").length&&a.closest(".a-input-text-wrapper").addClass("a-form-disabled")});
c.each(q.find("a"),function(a,b){a=c(b);a.hasClass("cvf-widget-link-disable-target")&&a.addClass("cvf-link-disabled")})}var k=this;g++;var v={success:"cvf:"+g+":success",error:"cvf:"+g+":error",content:"cvf:"+g+":content"};k.options={};c.extend(k.options,d,e);(function(a){if(1!==c(a.target).length)throw Error("The CVF widget requires a unique element.");if(!c.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!c.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");
})(k.options);var B=k.options.server,q=c(k.options.target);a.on(v.success,k.options.onSuccess);a.on(v.error,k.options.onError);a.on(v.content,k.options.onContent);k.start=function(){var b=B+"/ap/cvf/request.embed",d=k.options.requestToken,e=k.options.requestArbToken,f=k.options.associationHandle,g=k.options.language,m=0===c.trim(d).length,n=0===c.trim(e).length;if(m&&n)throw Error("The CVF widget requires a request token or arb token.");m=0!==c.trim(f).length;var r=0!==c.trim(g).length,p={};n?p.requestToken=
d:p.arb=e;p.CVFVersion=l.version;p.AUIVersion=P.AUI_BUILD_DATE;r&&(p.language=g);m&&(p["openid.assoc_handle"]=f);"string"===typeof k.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uet("bb",k.options.widgetMetricsScope,{wb:1});a.ajax(b,{method:"GET",params:p,success:h,error:A(k.start)})};k.destroy=function(){q.html("")};w();var C=0;k.options.autoStart&&k.start()}function f(a){return new e(a)}var c=a.$,d={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,
onError:void 0,onContent:function(){},spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0,associationHandle:void 0,language:void 0,showICALoadingAnimationOnSuccess:!1,showICAClaimUIOnClickChangeLink:!1},g=0;a.on("cvf:verification:request",function(b){var d=c("#"+b),e=d.data("token"),g=d.data("spinnerId");g=c("#"+g);f({target:d,spinnerTarget:g,requestToken:e,onSuccess:function(d,c,e){a.trigger("cvf:verification:complete:"+b,d,c,e)},onError:function(d){a.trigger("cvf:verification:error:"+
b,d)},autoStart:!0,autoDestroy:!1})});return{create:f}});"use strict";
P.when("A","ready").register("cvfFormDataGenerator",function(a){var l=a.$;return{retrieveFormData:function(a,m){a=l(a).closest(".cvf-widget-form");m&&(a=l(".cvf-widget-form-resend"));return{requestPath:a.data("use-only-form-action")?a.attr("action"):"/ap/cvf/"+a.attr("action")+".embed",inputData:a.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:a}},getNameValue:function(a){a=l(a);var b=a.attr("name");b||(b=a.closest(".cvf-widget-btn-val").attr("data-name"));var e=
a.attr("value");e||(e=a.closest(".cvf-widget-btn-val").attr("data-value"));return{name:b,value:e}}}});"use strict";
P.when("A","cvf","ready").execute(function(a,l){var b=a.$;b(document).ready(function(){function a(a,b,d){window.location=d;console.log("Client Side: "+a)}function e(a){console.log(a)}var f=b(".cvf-widget-spinner"),c=b("#cvf-widget-content");if(1===c.length){var d=b('[name\x3d"requestToken"]').first().attr("value");l.create({target:c,spinnerTarget:f,requestToken:d,onSuccess:a,onError:e,autoStart:!1})}})});"use strict";
P.when("A","ready").register("phoneFormField",function(a){function l(){a:{for(var a=b("select[name\x3d'cvf_phone_cc']").val()||"",f=0;f<m.length;f++){var c=m[f];if(a.toUpperCase()===c){b("#mobileClaimDisclosureMessage").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessageRelaxed").addClass("aok-hidden").hide();break a}}b("#mobileClaimDisclosureMessageRelaxed").removeClass("a-hidden aok-hidden").show();b("#mobileClaimDisclosureMessage").addClass("aok-hidden").hide()}}var b=a.$,
m=["US","CA","FR"];0<b("select[name\x3d'cvf_phone_cc']").length&&0<b("#mobileClaimDisclosureMessage").length&&0<b("#mobileClaimDisclosureMessageRelaxed").length&&(l(),b("select[name\x3d'cvf_phone_cc']").change(l))});"use strict";P.when("A").execute(function(a){a.declarative("auth-popup","click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=window.open(a.href,a.target,b.windowOptions))&&b.focus()})});
P.register("android-sms-otp-parser",function(){return{parseOtpCode:function(a){if(a&&(a=a.match(/(([\s\S]*[^0-9])|(^))([0-9]{4,6})[^0-9][\s\S]*[a-zA-Z0-9+\\\/]{11}/)||[],0<a.length))return a[4]}}});
P.when("A","mobile-auth-platform","3p-promise","android-sms-otp-parser","cvf-client-side-counters-util","ready").register("sms-retriever-handler",function(a,l,b,m,e){function f(a){(g=a.isSupported)?e.incrementCounter(d.ENABLED):e.incrementCounter(d.DISABLED);p={appHash:a.appHash}}function c(){return new b(function(a){p?a(p):l.isSmsRetrieverEnabled(function(b){f(b);a(p)})})}var d=Object.freeze({ENABLED:"SmsRetrieverEnabled",DISABLED:"SmsRetrieverDisabled",SMS_LISTENER_FAILED:"SmsRetrieverListenerFailedToRegister",
RECEIVED_INVALID_SMS:"SmsRetrieverListenerReceivedInvalidSms",RECEIVED_VALID_SMS:"SmsRetrieverListenerReceivedValidSms"}),g=null,p=null;return{isEnabled:function(){return new b(function(a){null!==g?a(g):l.isSmsRetrieverEnabled(function(b){f(b);a(g)})})},registerListener:function(a){return new b(function(b){l.registerMAPSmsReceiver(function(b){b.isRegistered?(b=m.parseOtpCode(b.sms))?(e.incrementCounter(d.RECEIVED_VALID_SMS),a(b)):e.incrementCounter(d.RECEIVED_INVALID_SMS):e.incrementCounter(d.SMS_LISTENER_FAILED)});
c().then(function(a){g?b({handlerCapability:"smsRetriever",handlerQueryParams:a}):b({})})})}}});"use strict";
P.when("A","a-spinner","ready").execute(function(a,l){function b(){f(".otp-input-box").attr("disabled","disabled");f("input[name\x3d'code']").val(m());(null!==f(".otp-input-box-container").data("isembed")?f(".otp-input-box-container").data("isembed"):1)?f(".cvf-widget-btn-verify").click():(a.capabilities.isAmazonApp||l("#otp-input-spinner").show(),f("#verification-code-form").submit())}function m(){var a="";f("input[name^\x3dotc]").each(function(b){a+=f(this).val()});return a}function e(){f(".cvf-widget-alert").is(":visible")&&
(f(".otp-input-box").removeClass("otp-input-box-alert"),f(".cvf-widget-alert").hide())}var f=a.$,c=/^\d+$/;a.declarative("otp-inputbox-handler","focusin",function(a){a=a.$target;a.is(".otp-input-box")&&(a.attr("name").match("otc-1")||""===a.prev().val()&&a.prev().focus())});a.declarative("otp-inputbox-handler","keyup",function(a){var d=a.$event;a=a.$target;a.is(".otp-input-box")&&(d=d.which||d.keyCode,-1===[16,9,224,18,17].indexOf(d))&&(-1!==[8,37,46].indexOf(d)?a.prev()&&!a.attr("name").match("otc-1")&&
(a.val(""),a.prev().select()):c.test(a.val())?a.attr("name").match("otc-6")?b():a.next()&&(e(),a.next().select()):a.val(""))});f(".otp-input-box").live("input",function(a){a=f(a.target);var c=a.val();e();if(1!==c.length)for(var d=0;d<c.length;d++){a.val(c.charAt(d));if(a.attr("name").match("otc-6")){b();break}a=a.next();a.focus()}});a.declarative("otp-inputbox-handler","click",function(){f("input[name^\x3dotc]").each(function(a){""===f(this).val()&&f(this).focus()})})});"use strict";
P.when("A","ready").execute(function(a){function l(a,b){b=Array.from((new Intl.NumberFormat(b,{useGrouping:!1})).format(9876543210)).reverse();var e=new Map(b.map(function(a,b){return[a,b]}));return a.split("").map(function(a){return e.has(a)?e.get(a):a}).join("")}a=a.$;var b=["ar-AE-u-nu-arab"];a("#ap_email, #ap_email_login, #auth-pv-enter-code, #cvf-input-code").keyup(function(){if(this.value){var a=this;b.map(function(b){a.value=l(a.value,b)})}})});